version: '3.9'

services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7134:7134"
    depends_on:
      - postgres
    networks:
      - db_network

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network
    command: [ "postgres", "-c", "log_destination=stderr", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql" ]

networks:
  db_network:
    driver: bridge

volumes:
  postgres_data:
